steps:

# Uses the docker build step to build an image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:latest', '.']

# Tag an image
- name: gcr.io/cloud-builders/docker
  args: ['tag',
    'gcr.io/$PROJECT_ID/terraform:oldtag',
    'gcr.io/$PROJECT_ID/terraform:$TAG_NAME']

# my-image is pushed to Container Registry
images: [
    'gcr.io/$PROJECT_ID/terraform:latest',
    'gcr.io/$PROJECT_ID/terraform:$TAG_NAME'
]
